version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: demo
            MYSQL_ROOT_PASSWORD: sassofono96
            MYSQL_ROOT_HOST: "%"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            custom_network:
                ipv4_address: 172.20.0.2
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s

    spring-boot-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: spring-boot-app
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: sassofono96
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        networks:
            custom_network:
                ipv4_address: 172.20.0.3

volumes:
    db_data:

networks:
    custom_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
